# deploy/setup_watchdog.ps1
# Full auto-recovery: worker restarts after process death, power blips, internet drops.
# No admin needed. Run once. Three layers of resilience:
#   1. Watchdog loop (every 2min PID check) - catches silent crashes
#   2. Task Scheduler at-logon trigger - catches reboots/logouts
#   3. Windows Startup folder shortcut - fires even before Task Scheduler is ready
#
# For power-blip full recovery without anyone logging in:
#   Enable Windows auto-login: run `netplwiz` -> uncheck "Users must enter password"

param([string]$RepoRoot = $env:FACTORY_REPO)
if (-not $RepoRoot) { $RepoRoot = Split-Path $PSScriptRoot -Parent }

$workerCtl      = Join-Path $RepoRoot "deploy\worker-ctl.ps1"
$pidFile        = Join-Path $RepoRoot "logs\worker.pid"
$logsDir        = Join-Path $RepoRoot "logs"
$watchdogScript = Join-Path $logsDir "watchdog.ps1"
New-Item -ItemType Directory -Force -Path $logsDir | Out-Null

# -- Layer 1: write the watchdog loop script -----------------------------------
Set-Content $watchdogScript @"
# Factory worker watchdog - auto-generated by setup_watchdog.ps1
`$PidFile   = '$pidFile'
`$WorkerCtl = '$workerCtl'
`$Log       = '$logsDir\watchdog.log'
function wlog(`$m) {
    `$line = "`$(Get-Date -f 'yyyy-MM-dd HH:mm:ss') `$m"
    Add-Content -Path `$Log -Value `$line -ErrorAction SilentlyContinue
}
wlog "Watchdog started (PID `$PID)"
while (`$true) {
    Start-Sleep -Seconds 120
    `$alive = `$false
    if (Test-Path `$PidFile) {
        `$wpid = (Get-Content `$PidFile -ErrorAction SilentlyContinue | Select-Object -First 1).Trim()
        if (`$wpid -match '^\d+`$') {
            `$alive = `$null -ne (Get-Process -Id ([int]`$wpid) -ErrorAction SilentlyContinue)
        }
    }
    if (-not `$alive) {
        wlog "Worker not running - starting via worker-ctl.ps1"
        & powershell.exe -NoProfile -ExecutionPolicy Bypass -File `$WorkerCtl start
        wlog "Start triggered"
    }
}
"@
Write-Host "[watchdog] Loop script written to $watchdogScript"

# -- Layer 2: Task Scheduler - at logon + every 5min repetition ---------------
$taskName = "FactoryWorkerWatchdog"
$action   = New-ScheduledTaskAction -Execute "powershell.exe" `
    -Argument "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$watchdogScript`""

# Primary trigger: at logon (fires on every login after reboot/power-blip)
$triggerLogon = New-ScheduledTaskTrigger -AtLogOn

$settings = New-ScheduledTaskSettingsSet `
    -ExecutionTimeLimit (New-TimeSpan -Hours 0) `
    -MultipleInstances IgnoreNew `
    -RestartCount 99 -RestartInterval (New-TimeSpan -Minutes 2) `
    -StartWhenAvailable

Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue
Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $triggerLogon `
    -Settings $settings -RunLevel Limited | Out-Null
Write-Host "[watchdog] Task Scheduler entry '$taskName' created (at-logon)"

# Start it right now
Start-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
Write-Host "[watchdog] Watchdog started immediately"

# -- Layer 3: Startup folder shortcut - belt-and-suspenders for reboots --------
$startupDir = [System.Environment]::GetFolderPath('Startup')  # no admin needed
$shortcutPath = Join-Path $startupDir "FactoryWorker.lnk"
try {
    $wsh = New-Object -ComObject WScript.Shell
    $sc  = $wsh.CreateShortcut($shortcutPath)
    $sc.TargetPath       = "powershell.exe"
    $sc.Arguments        = "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$workerCtl`" start"
    $sc.WorkingDirectory = $RepoRoot
    $sc.Description      = "Factory worker auto-start"
    $sc.Save()
    Write-Host "[watchdog] Startup folder shortcut created: $shortcutPath"
} catch {
    Write-Host "[watchdog] Startup shortcut failed (non-fatal): $_"
}

# -- Also start the worker now if not already running -------------------------
$pidNow = if (Test-Path $pidFile) { (Get-Content $pidFile).Trim() } else { "" }
$workerAlive = $pidNow -match '^\d+$' -and (Get-Process -Id ([int]$pidNow) -ErrorAction SilentlyContinue)
if (-not $workerAlive) {
    Write-Host "[watchdog] Worker not running - starting now..."
    & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $workerCtl start
} else {
    Write-Host "[watchdog] Worker already running (PID $pidNow)"
}

Write-Host ""
Write-Host "=============================================="
Write-Host "AUTO-RECOVERY FULLY SET UP:"
Write-Host "  Layer 1: Watchdog loop checks every 2min"
Write-Host "  Layer 2: Task Scheduler fires at every logon"
Write-Host "  Layer 3: Startup folder shortcut on reboot"
Write-Host ""
Write-Host "For POWER BLIP full recovery (no login needed):"
Write-Host "  Run: netplwiz -> uncheck 'Users must enter a password'"
Write-Host "  This auto-logs in panda on reboot -> Layers 2+3 fire"
Write-Host "=============================================="
