#!/usr/bin/env python3
"""Deterministic finalize step for the "already-happening" cinematic Shorts (v17).

Sibling of scripts/finalize_episode.py (claude-tricks), but for a channel whose
motion footage CANNOT be generated headlessly: Leonardo's generation API is
402-blocked, so the 6 Wan 2.6 motion clips are generated by a human in the
Chrome web UI (see channels/already-happening/PRODUCTION-BLUEPRINT.md §4). The
worker's produce_preview session therefore stops at an ANIMATIC (VO + captions
over black placeholder beds) and leaves a MOTION-TODO.md sentinel listing the 6
prompts. THIS script refuses to arm until that sentinel is gone and the 6 real
clips are on disk — that is the enforced manual gate.

Sequence:
  produce_preview (Claude, headless) -> script + VO + build_ep<ep>.py +
      black placeholders + animatic (the Studio preview) + MOTION-TODO.md
  ↓ (human generates 6 Wan 2.6 clips in Chrome, drops them into the motion dir,
     deletes MOTION-TODO.md — see channels/already-happening/episodes/ep<ep>.json)
  finalize_already_happening.py (this script, ~$0 Claude):
      1. GATE: MOTION-TODO.md must be gone + all 6 motion clips present & real.
      2. RENDER the real cut via channels/already-happening/build_ep<ep>.py.
      3. Ensure a web-delivery encode (crf 21 / maxrate 12M / faststart).
      4. LUFS QC (-14 ±0.5 LU — the channel spine).
      5. (Optional) arm YouTube via scripts/yt_upload.py --channel already-happening
         --publish-at <ISO UTC>, then sync the factory DB + advance the ep counter.

Called via the factory-worker shell_script job type: meta.script_path =
'scripts/finalize_already_happening.py', meta.script_args = ['--ep','<ep>',
'--schedule','<iso>','--calendar-id','<id>', ...].

Exit codes:
  0 -- rendered, QC passed, YT armed (if requested)
  1 -- render / config failure
  2 -- gate failed (motion clips missing / MOTION-TODO.md still present) or QC failed
  3 -- YT arm failed (render + QC succeeded, upload is the issue)
"""
import argparse
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, ".."))
CH = os.path.join(REPO, "channels", "already-happening")

# Channel spine — matches build_ep01_v3.py's loudnorm=I=-14 master + the
# network-wide -14 LUFS reference-loudness ratchet (see finalize_episode.py).
LUFS_TARGET = -14.0
LUFS_TOLERANCE = 0.5
# A real Wan 2.6 clip is ~1-4 MB; the black animatic placeholders are tiny.
# Anything under this is almost certainly still a placeholder.
MIN_MOTION_BYTES = 200_000


def run(cmd, **kw):
    print(">> " + " ".join(str(c) for c in cmd), flush=True)
    return subprocess.run(cmd, check=False, **kw)


def measure_lufs(path):
    """Integrated loudness via ffmpeg ebur128 (Summary block only). None on failure."""
    r = subprocess.run(
        ["ffmpeg", "-nostats", "-i", path, "-af", "ebur128=peak=true", "-f", "null", "-"],
        capture_output=True, text=True)
    tail = r.stderr.rsplit("Summary:", 1)[-1] if "Summary:" in r.stderr else ""
    m = re.search(r"Integrated loudness:\s*\n?\s*I:\s*(-?[\d.]+)\s+LUFS", tail)
    if not m:
        matches = re.findall(r"I:\s*(-?[\d.]+)\s+LUFS", r.stderr)
        if not matches:
            return None
        try:
            return float(matches[-1])
        except ValueError:
            return None
    try:
        return float(m.group(1))
    except ValueError:
        return None


def load_manifest(ep):
    """Read channels/already-happening/episodes/ep<ep>.json (written by the
    produce_preview session). Returns a dict with sensible fallbacks so a
    partial/missing manifest still finalizes."""
    p = os.path.join(CH, "episodes", f"ep{ep}.json")
    man = {}
    if os.path.exists(p):
        try:
            with open(p) as f:
                man = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            print(f">> WARNING: could not read manifest {p}: {e}")
    man.setdefault("ep", ep)
    man.setdefault("builder", f"build_ep{ep}.py")
    man.setdefault("motion_dir", os.path.join("assets", f"ep{ep}", "motion"))
    man.setdefault("motion_clips", [f"beat{i}.mp4" for i in range(1, 7)])
    return man


def gate_motion(man):
    """The manual-motion gate. Returns (ok, [issues]). Fails if the MOTION-TODO.md
    sentinel is still present, or any of the 6 real motion clips is missing/tiny."""
    issues = []
    mot = man["motion_dir"]
    mot_abs = mot if os.path.isabs(mot) else os.path.join(CH, mot)

    # sentinel lives next to the clips OR one level up in assets/ep<ep>/
    todo_candidates = [
        os.path.join(mot_abs, "MOTION-TODO.md"),
        os.path.join(os.path.dirname(mot_abs.rstrip("/")), "MOTION-TODO.md"),
    ]
    still = next((t for t in todo_candidates if os.path.exists(t)), None)
    if still:
        issues.append(
            f"MOTION-TODO.md still present ({still}) — generate the 6 Wan 2.6 clips "
            f"in Chrome (prompts are in the file / episodes/ep{man['ep']}.json), drop "
            f"them into {mot}, then delete MOTION-TODO.md before finalizing.")

    for clip in man["motion_clips"]:
        cp = os.path.join(mot_abs, clip)
        if not os.path.exists(cp):
            issues.append(f"motion clip missing: {os.path.join(mot, clip)}")
        elif os.path.getsize(cp) < MIN_MOTION_BYTES:
            issues.append(
                f"motion clip looks like a placeholder (<{MIN_MOTION_BYTES} bytes): "
                f"{os.path.join(mot, clip)} — replace it with the real Wan 2.6 render")
    return (not issues), issues


def find_output(ep, man):
    """Locate the delivery file the builder produced. Prefer an explicit manifest
    'output', then the standard web/raw stems. Returns an absolute path or None."""
    cands = []
    if man.get("output"):
        cands.append(man["output"])
    cands += [
        os.path.join("renders", f"ep{ep}", f"ep{ep}_web.mp4"),
        os.path.join("renders", f"ep{ep}", f"ep{ep}_v3_web.mp4"),
        os.path.join("renders", f"ep{ep}", f"ep{ep}.mp4"),
        os.path.join("renders", f"ep{ep}", f"ep{ep}_v3.mp4"),
    ]
    for c in cands:
        cp = c if os.path.isabs(c) else os.path.join(CH, c)
        if os.path.exists(cp):
            return cp
    return None


def web_encode(src):
    """Delivery encode per PRODUCTION-BLUEPRINT §5 if the builder only left a raw.
    Returns the web path (may equal src if already a _web file)."""
    if src.endswith("_web.mp4"):
        return src
    dst = src[:-4] + "_web.mp4"
    r = run(["ffmpeg", "-y", "-i", src,
             "-c:v", "libx264", "-crf", "21", "-preset", "slow", "-maxrate", "12M",
             "-bufsize", "24M", "-pix_fmt", "yuv420p", "-movflags", "+faststart",
             "-c:a", "aac", "-b:a", "192k", "-ar", "48000", dst])
    if r.returncode != 0 or not os.path.exists(dst):
        print(">> note: web-encode failed; delivering the builder output as-is")
        return src
    return dst


def arm_youtube(final_path, schedule_iso, man, desc_file, thumb_path=None, dry=False):
    yt_upload = os.path.join(HERE, "yt_upload.py")
    if not os.path.exists(yt_upload):
        return False, "yt_upload.py not found", None
    title = man.get("title") or os.path.basename(final_path)
    tags = man.get("tags") or ""
    cmd = ["python3", yt_upload, "--channel", "already-happening",
           "--video", final_path,
           "--title", title,
           "--tags", tags,
           "--audience", "general",
           "--synthetic",              # AI-generated footage → disclose
           "--privacy", "private",     # yt_upload flips public at publishAt
           "--publish-at", schedule_iso]
    if desc_file and os.path.exists(desc_file):
        cmd += ["--desc-file", desc_file]
    if thumb_path and os.path.exists(thumb_path):
        cmd += ["--thumbnail", thumb_path]
    if dry:
        cmd += ["--dry"]
    r = run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        return False, f"yt_upload exited {r.returncode}:\nSTDOUT:\n{r.stdout}\nSTDERR:\n{r.stderr}", None
    m = re.search(r"youtu\.be/([A-Za-z0-9_-]{6,})", r.stdout or "")
    return True, r.stdout.strip(), (m.group(1) if m else None)


def sync_factory_db(calendar_id, video_id, schedule_iso, man, final_path, desc_file=None):
    """Insert a scheduled factory_posts row + flip the calendar item to produced.
    Best-effort: the video is already armed on YouTube, so a DB hiccup here must
    NOT fail the job (prints a manual fallback)."""
    try:
        sys.path.insert(0, HERE)
        from factory_worker import Supa, load_env  # noqa: E402
        env = load_env()
        supa = Supa(env["SUPABASE_URL"], env["SUPABASE_SERVICE_KEY"])
    except Exception as e:  # noqa: BLE001
        print(f">> WARNING: factory DB sync skipped (could not init Supa): {e}")
        return False
    tags = [t.strip() for t in (man.get("tags") or "").split(",") if t.strip()]
    yt_desc = ""
    if desc_file and os.path.exists(desc_file):
        try:
            with open(desc_file) as f:
                yt_desc = f.read().strip()
        except OSError:
            pass
    row = {
        "channel_key": "already-happening",
        "local_path": final_path,
        "yt_title": (man.get("title") or os.path.basename(final_path))[:100],
        "yt_description": yt_desc,
        "tags": tags,
        "audience": "general",
        "synthetic": True,
        "publish_at": schedule_iso,
        "video_id": video_id,
        "status": "scheduled",
    }
    ok = True
    try:
        supa.insert("factory_posts", [row])
        print(f">> factory DB: factory_posts row inserted (scheduled, video {video_id})")
    except Exception as e:  # noqa: BLE001
        ok = False
        print(f">> WARNING: could not insert factory_posts row: {e}")
        print(f">> MANUAL FALLBACK: insert a factory_posts row (status=scheduled, "
              f"video_id={video_id}, publish_at={schedule_iso}) yourself.")
    if calendar_id:
        try:
            supa.patch("factory_calendar", f"id=eq.{calendar_id}", {"status": "produced"})
            print(f">> factory DB: calendar item {calendar_id} -> produced")
        except Exception as e:  # noqa: BLE001
            ok = False
            print(f">> WARNING: could not flip calendar {calendar_id} to produced: {e}")
    try:
        supa.insert("factory_events", [{
            "kind": "post_scheduled",
            "message": f"finalize armed already-happening: {row['yt_title']!r} "
                       f"(video {video_id}, publish {schedule_iso})",
            "meta": {"calendar_id": calendar_id, "video_id": video_id,
                     "channel_key": "already-happening",
                     "source": "finalize_already_happening.py"},
        }])
    except Exception:  # noqa: BLE001
        pass
    return ok


def advance_counter(ep):
    if not str(ep).isdigit():
        return
    try:
        sys.path.insert(0, HERE)
        from factory_worker import Supa, load_env  # noqa: E402
        env = load_env(); supa = Supa(env["SUPABASE_URL"], env["SUPABASE_SERVICE_KEY"])
        cur = supa.select("factory_settings",
                          "key=eq.already-happening_last_ep&select=value")
        curn = int(cur[0]["value"]) if cur and str(cur[0].get("value") or "").isdigit() else 0
        if int(ep) > curn:
            supa.insert("factory_settings",
                        [{"key": "already-happening_last_ep", "value": str(int(ep))}],
                        on_conflict="key", resolution="merge-duplicates")
            print(f">> ep counter -> already-happening_last_ep={int(ep)}")
    except Exception as e:  # noqa: BLE001
        print(f">> WARNING: could not advance ep counter: {e}")


def main():
    ap = argparse.ArgumentParser(
        description="Finalize an already-happening episode: gate motion + render + QC + arm YT")
    ap.add_argument("--ep", required=True, help="episode key (same as produce_preview meta.ep)")
    ap.add_argument("--tag", default="v3", help="unused stem hint (kept for parity)")
    ap.add_argument("--schedule", help="ISO 8601 UTC publish time to arm YouTube")
    ap.add_argument("--skip-arm", action="store_true", help="render + QC only")
    ap.add_argument("--dry", action="store_true", help="pass --dry to yt_upload")
    ap.add_argument("--calendar-id", help="factory_calendar id (DB sync on successful arm)")
    a = ap.parse_args()

    man = load_manifest(a.ep)

    # 1) MANUAL-MOTION GATE
    ok, issues = gate_motion(man)
    if not ok:
        print("!! motion gate FAILED — the 6 Wan 2.6 clips are not ready:", file=sys.stderr)
        for i in issues:
            print(f"  - {i}", file=sys.stderr)
        sys.exit(2)
    print(">> motion gate PASSED — 6 real clips present, MOTION-TODO.md cleared")

    # 2) RENDER the real cut
    builder = os.path.join(CH, man["builder"])
    if not os.path.exists(builder):
        print(f"!! builder not found: {builder}", file=sys.stderr)
        sys.exit(1)
    r = run(["python3", builder])
    if r.returncode != 0:
        print(f"!! builder exited {r.returncode}", file=sys.stderr)
        sys.exit(1)

    raw = find_output(a.ep, man)
    if not raw:
        print(f"!! no rendered output found under channels/already-happening/renders/ep{a.ep}/",
              file=sys.stderr)
        sys.exit(1)

    # 3) DELIVERY ENCODE
    final = web_encode(raw)

    # 4) LUFS QC
    lufs = measure_lufs(final)
    if lufs is None:
        print(">> WARNING: could not measure LUFS (continuing)")
    else:
        drift = lufs - LUFS_TARGET
        print(f">> LUFS integrated: {lufs:.2f} (target {LUFS_TARGET}, drift {drift:+.2f} LU)")
        if abs(drift) > LUFS_TOLERANCE:
            print(f"!! QC gate FAILED: LUFS {lufs:.2f} is {abs(drift):.2f} LU off spine "
                  f"{LUFS_TARGET} (±{LUFS_TOLERANCE})", file=sys.stderr)
            sys.exit(2)
    print(">> QC gate PASSED")

    # 5) ARM (optional)
    if a.skip_arm or not a.schedule:
        print(">> skipping YT arm (no --schedule or --skip-arm)")
        print(f">> final ready at: {final}")
        sys.exit(0)

    desc_file = None
    for cand in (man.get("description_path"),
                 os.path.join("episodes", f"ep{a.ep}_description.txt")):
        if not cand:
            continue
        cp = cand if os.path.isabs(cand) else os.path.join(CH, cand)
        if os.path.exists(cp):
            desc_file = cp
            break
    thumb = None
    for cand in (os.path.join(CH, "renders", f"ep{a.ep}", f"thumb_ep{a.ep}.jpg"),
                 os.path.join(CH, "assets", f"ep{a.ep}", "thumbnail.jpg")):
        if os.path.exists(cand):
            thumb = cand
            break

    ok, msg, video_id = arm_youtube(final, a.schedule, man, desc_file, thumb, dry=a.dry)
    if not ok:
        print(f"!! YT arm FAILED: {msg}", file=sys.stderr)
        sys.exit(3)
    print(f">> YT armed for {a.schedule}: {msg}")

    if a.calendar_id and not a.dry:
        if video_id:
            sync_factory_db(a.calendar_id, video_id, a.schedule, man, final, desc_file)
        else:
            print(">> WARNING: armed but no video_id parsed — factory DB not synced.")
    if not a.dry:
        advance_counter(a.ep)

    print(f">> DONE — final at {final}, scheduled {a.schedule}"
          + (f", video {video_id}" if video_id else ""))


if __name__ == "__main__":
    main()
