# deploy/gpu/schedule_maint.ps1
# Register a WEEKLY Windows Scheduled Task that runs `disk_maint.ps1 -Clean` so the
# pip/HF/temp caches never balloon again. No admin (RunLevel Limited). Survives
# reboots; StartWhenAvailable so a missed run (box was off) fires when next on.
# Writes a small wrapper (mirrors setup_watchdog.ps1) so the task can use -File and
# append output to logs\disk_maint.log. Prints SCHEDULE_OK. Run once on the worker.
#
# worker: powershell.exe -NonInteractive -File <this> -RepoRoot <REPO>
param([string]$RepoRoot)
$ErrorActionPreference = "Continue"
$Repo = if ($RepoRoot) { $RepoRoot } else { Split-Path -Parent (Split-Path -Parent $PSScriptRoot) }
$logsDir = Join-Path $Repo "logs"; New-Item -ItemType Directory -Force -Path $logsDir | Out-Null
$dm  = Join-Path $Repo "deploy\gpu\disk_maint.ps1"
$log = Join-Path $logsDir "disk_maint.log"
$wrapper = Join-Path $logsDir "disk_cleanup_task.ps1"
if (-not (Test-Path $dm)) { Write-Host "SCHEDULE_FAIL disk_maint.ps1 not found at $dm"; exit 1 }

# wrapper the task runs: header + disk_maint -Clean, all output appended to $log.
# Backtick-escaped $ / " stay literal so they evaluate at RUN time, not now; $log
# $dm $Repo are expanded now to bake in the paths.
@"
# auto-generated by schedule_maint.ps1 - weekly disk cleanup
`"=== `$(Get-Date -Format o) weekly disk cleanup ===`" | Add-Content -Path '$log'
& '$dm' -RepoRoot '$Repo' -Clean *>> '$log'
"@ | Set-Content -Encoding UTF8 $wrapper

$taskName = "FactoryDiskCleanup"
$action = New-ScheduledTaskAction -Execute "powershell.exe" `
  -Argument ("-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$wrapper`"")
$trigger = New-ScheduledTaskTrigger -Weekly -DaysOfWeek Sunday -At ([datetime]"04:00")
$settings = New-ScheduledTaskSettingsSet -StartWhenAvailable `
  -ExecutionTimeLimit (New-TimeSpan -Hours 1) -MultipleInstances IgnoreNew
Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue
try {
  Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger `
    -Settings $settings -RunLevel Limited | Out-Null
} catch {
  Write-Host ("SCHEDULE_FAIL " + $_.Exception.Message); exit 1
}
Write-Host "SCHEDULE_OK task=$taskName schedule='weekly Sun 04:00' wrapper=$wrapper log=$log"
exit 0
